# Generated by Django 2.0.3 on 2018-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('adresa', models.CharField(max_length=30)),
                ('localitate', models.CharField(max_length=30)),
                ('judet', models.CharField(max_length=30)),
                ('cod_postal', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('telefon', models.IntegerField(max_length=12)),
                ('oferta', models.CharField(choices=[('1', 'Vreau Un Set - 2 Perechi - 99 RON'), ('2', 'Vreau Două Seturi - 178 RON'), ('3', 'Vreau Trei Seturi - 257 RON')], max_length=1)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
    ]
