# Generated by Django 2.0.3 on 2018-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cod_postal',
        ),
    ]
