# Generated by Django 2.0.3 on 2018-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_person_cod_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adresa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='judet',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='localitate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nume',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='oferta',
            field=models.CharField(choices=[('1', 'Vreau Un Set - 2 Perechi - 99 RON'), ('2', 'Vreau Două Seturi - 178 RON'), ('3', 'Vreau Trei Seturi - 257 RON')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefon',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
